apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: loadtest
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      hostname: elasticsearch
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
        - name: elasticsearch
          image: elasticsearch:7.9.1 # don't forget to adjust your requiments.txt file
          resources:
            requests:
              cpu: 1000m
              memory: 2500Mi
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2048m -Xmx2048m
          - name: discovery.type
            value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: loadtest
spec:
  ports:
  - port: 9200
  selector:
    app: elasticsearch